"""generate_tables

Revision ID: eb0a8eb0281e
Revises:
Create Date: 2025-05-26 08:53:34.375993

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "eb0a8eb0281e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estadistica",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ataque", sa.Integer(), nullable=False),
        sa.Column("defensa", sa.Integer(), nullable=False),
        sa.Column("ataque_especial", sa.Integer(), nullable=False),
        sa.Column("defensa_especial", sa.Integer(), nullable=False),
        sa.Column("puntos_de_golpe", sa.Integer(), nullable=False),
        sa.Column("velocidad", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "habilidad",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tipo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "debilidad",
        sa.Column("tipo_id", sa.Integer(), nullable=False),
        sa.Column("debilidad_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["debilidad_id"],
            ["tipo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["tipo.id"],
        ),
        sa.PrimaryKeyConstraint("tipo_id", "debilidad_id"),
    )
    op.create_table(
        "equipo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generacion_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generacion_id"],
            ["generacion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movimiento",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("categoria", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("potencia", sa.Integer(), nullable=False),
        sa.Column("precision", sa.Integer(), nullable=False),
        sa.Column("puntos_de_poder", sa.Integer(), nullable=False),
        sa.Column("efecto", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tipo_id", sa.Integer(), nullable=False),
        sa.Column("generacion_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generacion_id"],
            ["generacion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["tipo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("altura", sa.Float(), nullable=False),
        sa.Column("peso", sa.Float(), nullable=False),
        sa.Column("estadistica_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["estadistica_id"],
            ["estadistica.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evolucion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generacionpokemon",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("generacion_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generacion_id"],
            ["generacion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("pokemon_id", "generacion_id"),
    )
    op.create_table(
        "habilidadpokemon",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("habilidad_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["habilidad_id"],
            ["habilidad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("pokemon_id", "habilidad_id"),
    )
    op.create_table(
        "integrante",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("apodo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("equipo_id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipo_id"],
            ["equipo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("apodo"),
    )
    op.create_table(
        "movimientohuevo",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("movimiento_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movimiento_id"],
            ["movimiento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("pokemon_id", "movimiento_id"),
    )
    op.create_table(
        "movimientomaquina",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("movimiento_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movimiento_id"],
            ["movimiento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("pokemon_id", "movimiento_id"),
    )
    op.create_table(
        "movimientonivel",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("movimiento_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movimiento_id"],
            ["movimiento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("pokemon_id", "movimiento_id"),
    )
    op.create_table(
        "tipopokemon",
        sa.Column("tipo_id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["tipo.id"],
        ),
        sa.PrimaryKeyConstraint("tipo_id", "pokemon_id"),
    )
    op.create_table(
        "movimientointegrante",
        sa.Column("integrante_id", sa.Integer(), nullable=False),
        sa.Column("movimiento_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["integrante_id"],
            ["integrante.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movimiento_id"],
            ["movimiento.id"],
        ),
        sa.PrimaryKeyConstraint("integrante_id", "movimiento_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movimientointegrante")
    op.drop_table("tipopokemon")
    op.drop_table("movimientonivel")
    op.drop_table("movimientomaquina")
    op.drop_table("movimientohuevo")
    op.drop_table("integrante")
    op.drop_table("habilidadpokemon")
    op.drop_table("generacionpokemon")
    op.drop_table("evolucion")
    op.drop_table("pokemon")
    op.drop_table("movimiento")
    op.drop_table("equipo")
    op.drop_table("debilidad")
    op.drop_table("tipo")
    op.drop_table("habilidad")
    op.drop_table("generacion")
    op.drop_table("estadistica")
    # ### end Alembic commands ###
