from pydantic import HttpUrl

from app.pokemon.models.estadistica import Estadistica
from app.pokemon.models.generacion import Generacion
from app.pokemon.models.movimiento import MovimientoResumido
from app.pokemon.models.pokemon import Evolucion, Habilidad, Pokemon
from app.pokemon.models.tipo import PokemonTipo, Tipo
from app.utils.database import create_database
from app.utils.seed.generacion import load_generaciones
from app.utils.seed.movimiento import load_movimientos
from app.utils.seed.pokemon import (
    load_pokemon_estadisticas,
    load_pokemon_evoluciones,
    load_pokemon_habilidades,
    load_pokemon_movimientos,
    load_pokemon_tipos,
    load_pokemons,
)
from app.utils.seed.tipo import load_tipos


def test_load_pokemon():
    database = create_database()
    load_generaciones(database)
    load_tipos(database)
    load_movimientos(database)
    load_pokemons(database)
    load_pokemon_estadisticas(database)
    load_pokemon_tipos(database)
    load_pokemon_habilidades(database)
    load_pokemon_evoluciones(database)
    load_pokemon_movimientos(database)

    from pprint import pprint

    pprint(database["pokemons"][132])

    assert database["pokemons"][132] == Pokemon(
        id=133,
        nombre="eevee",
        imagen=HttpUrl(
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%3Cbuilt-in%20function%20id%3E.png"
        ),
        altura=3.0,
        peso=65.0,
        generaciones=[
            Generacion(id=1, nombre="Generación I"),
            Generacion(id=2, nombre="Generación II"),
            Generacion(id=3, nombre="Generación III"),
            Generacion(id=4, nombre="Generación IV"),
            Generacion(id=5, nombre="Generación V"),
            Generacion(id=6, nombre="Generación VI"),
            Generacion(id=7, nombre="Generación VII"),
            Generacion(id=8, nombre="Generación VIII"),
        ],
        tipos=[
            PokemonTipo(id=1, nombre="Normal", debilidades=[Tipo(id=2, nombre="Lucha")])
        ],
        habilidades=[
            Habilidad(id=50, nombre="Fuga"),
            Habilidad(id=91, nombre="Adaptable"),
            Habilidad(id=107, nombre="Anticipación"),
        ],
        estadisticas=Estadistica(
            ataque=55,
            defensa=50,
            ataque_especial=45,
            defensa_especial=65,
            puntos_de_golpe=55,
            velocidad=55,
        ),
        evoluciones=[
            Evolucion(
                id=134,
                nombre="vaporeon",
                imagen=HttpUrl(
                    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%3Cbuilt-in%20function%20id%3E.png"
                ),
            ),
            Evolucion(
                id=136,
                nombre="flareon",
                imagen=HttpUrl(
                    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%3Cbuilt-in%20function%20id%3E.png"
                ),
            ),
            Evolucion(
                id=135,
                nombre="jolteon",
                imagen=HttpUrl(
                    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%3Cbuilt-in%20function%20id%3E.png"
                ),
            ),
            Evolucion(
                id=196,
                nombre="espeon",
                imagen=HttpUrl(
                    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%3Cbuilt-in%20function%20id%3E.png"
                ),
            ),
            Evolucion(
                id=197,
                nombre="umbreon",
                imagen=HttpUrl(
                    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%3Cbuilt-in%20function%20id%3E.png"
                ),
            ),
            Evolucion(
                id=700,
                nombre="sylveon",
                imagen=HttpUrl(
                    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%3Cbuilt-in%20function%20id%3E.png"
                ),
            ),
            Evolucion(
                id=471,
                nombre="glaceon",
                imagen=HttpUrl(
                    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%3Cbuilt-in%20function%20id%3E.png"
                ),
            ),
            Evolucion(
                id=470,
                nombre="leafeon",
                imagen=HttpUrl(
                    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%3Cbuilt-in%20function%20id%3E.png"
                ),
            ),
        ],
        movimientos_huevo=[
            MovimientoResumido(
                id=321,
                nombre="Cosquillas",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Lowers the target's Attack and Defense by one stage.",
            ),
            MovimientoResumido(
                id=197,
                nombre="Detección",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=2, nombre="Lucha"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=5,
                efecto="Prevents any moves from hitting the user this turn.",
            ),
            MovimientoResumido(
                id=485,
                nombre="Sincrorruido",
                generacion=Generacion(id=5, nombre="Generación V"),
                tipo=Tipo(id=14, nombre="Psíquico"),
                categoria="especial",
                potencia=120,
                precision=100,
                puntos_de_poder=10,
                efecto="Hits any Pokémon that shares a type with the user.",
            ),
            MovimientoResumido(
                id=313,
                nombre="Llanto Falso",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=17, nombre="Siniestro"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Lowers the target's Special Defense by two stages.",
            ),
            MovimientoResumido(
                id=203,
                nombre="Aguante",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="Prevents the user's HP from lowering below 1 this turn.",
            ),
            MovimientoResumido(
                id=204,
                nombre="Encanto",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=18, nombre="Hada"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Lowers the target's Attack by two stages.",
            ),
            MovimientoResumido(
                id=363,
                nombre="Don Natural",
                generacion=Generacion(id=4, nombre="Generación IV"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=0,
                precision=100,
                puntos_de_poder=15,
                efecto="Power and type depend on the held berry.",
            ),
            MovimientoResumido(
                id=174,
                nombre="Maldición",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=8, nombre="Fantasma"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="Ghosts pay half their max HP to hurt the target every turn.  Others decrease Speed but raise Attack and Defense.",
            ),
            MovimientoResumido(
                id=175,
                nombre="Azote",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=0,
                precision=100,
                puntos_de_poder=15,
                efecto="Inflicts more damage when the user has less HP remaining, with a maximum of 200 power.",
            ),
            MovimientoResumido(
                id=273,
                nombre="Deseo",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="User will recover half its max HP at the end of the next turn.",
            ),
            MovimientoResumido(
                id=500,
                nombre="Poder Reserva",
                generacion=Generacion(id=5, nombre="Generación V"),
                tipo=Tipo(id=14, nombre="Psíquico"),
                categoria="especial",
                potencia=20,
                precision=100,
                puntos_de_poder=10,
                efecto="Power is higher the more the user's stats have been raised, to a maximum of 31×.",
            ),
            MovimientoResumido(
                id=189,
                nombre="Bofetón Lodo",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=5, nombre="Tierra"),
                categoria="especial",
                potencia=20,
                precision=100,
                puntos_de_poder=10,
                efecto="Has a $effect_chance% chance to lower the target's accuracy by one stage.",
            ),
            MovimientoResumido(
                id=343,
                nombre="Antojo",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=60,
                precision=100,
                puntos_de_poder=25,
                efecto="Takes the target's item.",
            ),
            MovimientoResumido(
                id=24,
                nombre="Doble Patada",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=2, nombre="Lucha"),
                categoria="físico",
                potencia=30,
                precision=100,
                puntos_de_poder=30,
                efecto="Hits twice in one turn.",
            ),
            MovimientoResumido(
                id=281,
                nombre="Bostezo",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="Target sleeps at the end of the next turn.",
            ),
            MovimientoResumido(
                id=445,
                nombre="Seducción",
                generacion=Generacion(id=4, nombre="Generación IV"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Lowers the target's Special Attack by two stages if it's the opposite gender.",
            ),
        ],
        movimientos_maquina=[
            MovimientoResumido(
                id=129,
                nombre="Rapidez",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="especial",
                potencia=60,
                precision=0,
                puntos_de_poder=20,
                efecto="Never misses.",
            ),
            MovimientoResumido(
                id=130,
                nombre="Cabezazo",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=130,
                precision=100,
                puntos_de_poder=10,
                efecto="Raises the user's Defense by one stage.  User charges for one turn before attacking.",
            ),
            MovimientoResumido(
                id=514,
                nombre="Represalia",
                generacion=Generacion(id=5, nombre="Generación V"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=70,
                precision=100,
                puntos_de_poder=5,
                efecto="Has double power if a friendly Pokémon fainted last turn.",
            ),
            MovimientoResumido(
                id=6,
                nombre="Día de Pago",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=40,
                precision=100,
                puntos_de_poder=20,
                efecto="Scatters money on the ground worth five times the user's level.",
            ),
            MovimientoResumido(
                id=263,
                nombre="Imagen",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=70,
                precision=100,
                puntos_de_poder=20,
                efecto="Power doubles if user is burned, paralyzed, or poisoned.",
            ),
            MovimientoResumido(
                id=526,
                nombre="Avivar",
                generacion=Generacion(id=5, nombre="Generación V"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=30,
                efecto="Raises the user's Attack and Special Attack by one stage each.",
            ),
            MovimientoResumido(
                id=270,
                nombre="Refuerzo",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=20,
                efecto="Ally's next move inflicts half more damage.",
            ),
            MovimientoResumido(
                id=156,
                nombre="Descanso",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=14, nombre="Psíquico"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="User sleeps for two turns, completely healing itself.",
            ),
            MovimientoResumido(
                id=29,
                nombre="Golpe Cabeza",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=70,
                precision=100,
                puntos_de_poder=15,
                efecto="Has a $effect_chance% chance to make the target flinch.",
            ),
            MovimientoResumido(
                id=34,
                nombre="Golpe Cuerpo",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=85,
                precision=100,
                puntos_de_poder=15,
                efecto="Has a $effect_chance% chance to [paralyze]{mechanic:paralysis} the target.",
            ),
            MovimientoResumido(
                id=290,
                nombre="Daño Secreto",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=70,
                precision=100,
                puntos_de_poder=20,
                efecto="Has a $effect_chance% chance to inflict a status effect which depends upon the terrain.",
            ),
            MovimientoResumido(
                id=36,
                nombre="Derribo",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=90,
                precision=85,
                puntos_de_poder=20,
                efecto="User receives 1/4 the damage it inflicts in recoil.",
            ),
            MovimientoResumido(
                id=164,
                nombre="Sustituto",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="Transfers 1/4 of the user's max HP into a doll, protecting the user from further damage or status changes until it breaks.",
            ),
            MovimientoResumido(
                id=38,
                nombre="Doble Filo",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=120,
                precision=100,
                puntos_de_poder=15,
                efecto="User receives 1/3 the damage inflicted in recoil.",
            ),
            MovimientoResumido(
                id=173,
                nombre="Ronquido",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="especial",
                potencia=50,
                precision=100,
                puntos_de_poder=15,
                efecto="Has a $effect_chance% chance to make the target flinch.  Only works if the user is sleeping.",
            ),
            MovimientoResumido(
                id=174,
                nombre="Maldición",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=8, nombre="Fantasma"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="Ghosts pay half their max HP to hurt the target every turn.  Others decrease Speed but raise Attack and Defense.",
            ),
            MovimientoResumido(
                id=304,
                nombre="Vozarrón",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="especial",
                potencia=90,
                precision=100,
                puntos_de_poder=10,
                efecto="Inflicts regular damage with no additional effect.",
            ),
            MovimientoResumido(
                id=182,
                nombre="Protección",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="Prevents any moves from hitting the user this turn.",
            ),
            MovimientoResumido(
                id=311,
                nombre="Meteorobola",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="especial",
                potencia=50,
                precision=100,
                puntos_de_poder=10,
                efecto="If there be weather, this move has doubled power and the weather's type.",
            ),
            MovimientoResumido(
                id=313,
                nombre="Llanto Falso",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=17, nombre="Siniestro"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Lowers the target's Special Defense by two stages.",
            ),
            MovimientoResumido(
                id=189,
                nombre="Bofetón Lodo",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=5, nombre="Tierra"),
                categoria="especial",
                potencia=20,
                precision=100,
                puntos_de_poder=10,
                efecto="Has a $effect_chance% chance to lower the target's accuracy by one stage.",
            ),
            MovimientoResumido(
                id=445,
                nombre="Seducción",
                generacion=Generacion(id=4, nombre="Generación IV"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Lowers the target's Special Attack by two stages if it's the opposite gender.",
            ),
            MovimientoResumido(
                id=197,
                nombre="Detección",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=2, nombre="Lucha"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=5,
                efecto="Prevents any moves from hitting the user this turn.",
            ),
            MovimientoResumido(
                id=203,
                nombre="Aguante",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="Prevents the user's HP from lowering below 1 this turn.",
            ),
            MovimientoResumido(
                id=204,
                nombre="Encanto",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=18, nombre="Hada"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Lowers the target's Attack by two stages.",
            ),
            MovimientoResumido(
                id=590,
                nombre="Confidencia",
                generacion=Generacion(id=6, nombre="Generación VI"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=20,
                efecto="Lowers the target's Special Attack by one stage.",
            ),
            MovimientoResumido(
                id=207,
                nombre="Contoneo",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=85,
                puntos_de_poder=15,
                efecto="Raises the target's Attack by two stages and confuses the target.",
            ),
            MovimientoResumido(
                id=213,
                nombre="Atracción",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=15,
                efecto="Target falls in love if it has the opposite gender, and has a 50% chance to refuse attacking the user.",
            ),
            MovimientoResumido(
                id=214,
                nombre="Sonámbulo",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="Randomly uses one of the user's other three moves.  Only works if the user is sleeping.",
            ),
            MovimientoResumido(
                id=216,
                nombre="Retribución",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Power increases with happiness, up to a maximum of 102.",
            ),
            MovimientoResumido(
                id=218,
                nombre="Frustración",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Power increases as happiness decreases, up to a maximum of 102.",
            ),
            MovimientoResumido(
                id=91,
                nombre="Excavar",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=5, nombre="Tierra"),
                categoria="físico",
                potencia=80,
                precision=100,
                puntos_de_poder=10,
                efecto="User digs underground, dodging all attacks, and hits next turn.",
            ),
            MovimientoResumido(
                id=92,
                nombre="Tóxico",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=4, nombre="Veneno"),
                categoria="estado",
                potencia=0,
                precision=90,
                puntos_de_poder=10,
                efecto="Badly poisons the target, inflicting more damage every turn.",
            ),
            MovimientoResumido(
                id=226,
                nombre="Relevo",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=40,
                efecto="Allows the trainer to switch out the user and pass effects along to its replacement.",
            ),
            MovimientoResumido(
                id=99,
                nombre="Furia",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=20,
                precision=100,
                puntos_de_poder=20,
                efecto="If the user is hit after using this move, its Attack rises by one stage.",
            ),
            MovimientoResumido(
                id=102,
                nombre="Mimético",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="Copies the target's last used move.",
            ),
            MovimientoResumido(
                id=231,
                nombre="Cola Férrea",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=9, nombre="Acero"),
                categoria="físico",
                potencia=100,
                precision=75,
                puntos_de_poder=15,
                efecto="Has a $effect_chance% chance to lower the target's Defense by one stage.",
            ),
            MovimientoResumido(
                id=104,
                nombre="Doble Equipo",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=15,
                efecto="Raises the user's evasion by one stage.",
            ),
            MovimientoResumido(
                id=363,
                nombre="Don Natural",
                generacion=Generacion(id=4, nombre="Generación IV"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=0,
                precision=100,
                puntos_de_poder=15,
                efecto="Power and type depend on the held berry.",
            ),
            MovimientoResumido(
                id=237,
                nombre="Poder Oculto",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="especial",
                potencia=60,
                precision=100,
                puntos_de_poder=15,
                efecto="Power and type depend upon user's IVs.  Power can range from 30 to 70.",
            ),
            MovimientoResumido(
                id=240,
                nombre="Danza Lluvia",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=11, nombre="Agua"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=5,
                efecto="Changes the weather to rain for five turns.",
            ),
            MovimientoResumido(
                id=241,
                nombre="Día Soleado",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=10, nombre="Fuego"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=5,
                efecto="Changes the weather to sunny for five turns.",
            ),
            MovimientoResumido(
                id=496,
                nombre="Canon",
                generacion=Generacion(id=5, nombre="Generación V"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="especial",
                potencia=60,
                precision=100,
                puntos_de_poder=15,
                efecto="Has double power if it's used more than once per turn.",
            ),
            MovimientoResumido(
                id=115,
                nombre="Reflejo",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=14, nombre="Psíquico"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=20,
                efecto="Reduces damage from physical attacks by half.",
            ),
            MovimientoResumido(
                id=497,
                nombre="Eco Voz",
                generacion=Generacion(id=5, nombre="Generación V"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="especial",
                potencia=40,
                precision=100,
                puntos_de_poder=15,
                efecto="Power increases by 100% for each consecutive use by any friendly Pokémon, to a maximum of 200.",
            ),
            MovimientoResumido(
                id=117,
                nombre="Venganza",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=0,
                precision=0,
                puntos_de_poder=10,
                efecto="User waits for two turns, then hits back for twice the damage it took.",
            ),
            MovimientoResumido(
                id=116,
                nombre="Foco Energía",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=30,
                efecto="Increases the user's chance to score a critical hit.",
            ),
            MovimientoResumido(
                id=247,
                nombre="Bola Sombra",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=8, nombre="Fantasma"),
                categoria="especial",
                potencia=80,
                precision=100,
                puntos_de_poder=15,
                efecto="Has a $effect_chance% chance to lower the target's Special Defense by one stage.",
            ),
            MovimientoResumido(
                id=500,
                nombre="Poder Reserva",
                generacion=Generacion(id=5, nombre="Generación V"),
                tipo=Tipo(id=14, nombre="Psíquico"),
                categoria="especial",
                potencia=20,
                precision=100,
                puntos_de_poder=10,
                efecto="Power is higher the more the user's stats have been raised, to a maximum of 31×.",
            ),
        ],
        movimientos_nivel=[
            MovimientoResumido(
                id=129,
                nombre="Rapidez",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="especial",
                potencia=60,
                precision=0,
                puntos_de_poder=20,
                efecto="Never misses.",
            ),
            MovimientoResumido(
                id=387,
                nombre="Última Baza",
                generacion=Generacion(id=4, nombre="Generación IV"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=140,
                precision=100,
                puntos_de_poder=5,
                efecto="Can only be used after all of the user's other moves have been used.",
            ),
            MovimientoResumido(
                id=270,
                nombre="Refuerzo",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=20,
                efecto="Ally's next move inflicts half more damage.",
            ),
            MovimientoResumido(
                id=24,
                nombre="Doble Patada",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=2, nombre="Lucha"),
                categoria="físico",
                potencia=30,
                precision=100,
                puntos_de_poder=30,
                efecto="Hits twice in one turn.",
            ),
            MovimientoResumido(
                id=28,
                nombre="Ataque Arena",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=5, nombre="Tierra"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=15,
                efecto="Lowers the target's accuracy by one stage.",
            ),
            MovimientoResumido(
                id=287,
                nombre="Alivio",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=20,
                efecto="Cleanses the user of a burn, paralysis, or poison.",
            ),
            MovimientoResumido(
                id=33,
                nombre="Placaje",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=40,
                precision=100,
                puntos_de_poder=35,
                efecto="Inflicts regular damage with no additional effect.",
            ),
            MovimientoResumido(
                id=36,
                nombre="Derribo",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=90,
                precision=85,
                puntos_de_poder=20,
                efecto="User receives 1/4 the damage it inflicts in recoil.",
            ),
            MovimientoResumido(
                id=38,
                nombre="Doble Filo",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=120,
                precision=100,
                puntos_de_poder=15,
                efecto="User receives 1/3 the damage inflicted in recoil.",
            ),
            MovimientoResumido(
                id=39,
                nombre="Látigo",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=30,
                efecto="Lowers the target's Defense by one stage.",
            ),
            MovimientoResumido(
                id=44,
                nombre="Mordisco",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=17, nombre="Siniestro"),
                categoria="físico",
                potencia=60,
                precision=100,
                puntos_de_poder=25,
                efecto="Has a $effect_chance% chance to make the target flinch.",
            ),
            MovimientoResumido(
                id=45,
                nombre="Gruñido",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=40,
                efecto="Lowers the target's Attack by one stage.",
            ),
            MovimientoResumido(
                id=204,
                nombre="Encanto",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=18, nombre="Hada"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=20,
                efecto="Lowers the target's Attack by two stages.",
            ),
            MovimientoResumido(
                id=343,
                nombre="Antojo",
                generacion=Generacion(id=3, nombre="Generación III"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=60,
                precision=100,
                puntos_de_poder=25,
                efecto="Takes the target's item.",
            ),
            MovimientoResumido(
                id=608,
                nombre="Ojitos Tiernos",
                generacion=Generacion(id=6, nombre="Generación VI"),
                tipo=Tipo(id=18, nombre="Hada"),
                categoria="estado",
                potencia=0,
                precision=100,
                puntos_de_poder=30,
                efecto="Lowers the target's Attack by one stage.",
            ),
            MovimientoResumido(
                id=98,
                nombre="Ataque Rápido",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="físico",
                potencia=40,
                precision=100,
                puntos_de_poder=30,
                efecto="Inflicts regular damage with no additional effect.",
            ),
            MovimientoResumido(
                id=226,
                nombre="Relevo",
                generacion=Generacion(id=2, nombre="Generación II"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=40,
                efecto="Allows the trainer to switch out the user and pass effects along to its replacement.",
            ),
            MovimientoResumido(
                id=116,
                nombre="Foco Energía",
                generacion=Generacion(id=1, nombre="Generación I"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=30,
                efecto="Increases the user's chance to score a critical hit.",
            ),
            MovimientoResumido(
                id=376,
                nombre="As Oculto",
                generacion=Generacion(id=4, nombre="Generación IV"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="especial",
                potencia=0,
                precision=0,
                puntos_de_poder=5,
                efecto="Power increases when this move has less PP, up to a maximum of 200.",
            ),
            MovimientoResumido(
                id=383,
                nombre="Copión",
                generacion=Generacion(id=4, nombre="Generación IV"),
                tipo=Tipo(id=1, nombre="Normal"),
                categoria="estado",
                potencia=0,
                precision=0,
                puntos_de_poder=20,
                efecto="Uses the target's last used move.",
            ),
        ],
    )
